export type DeveloperProspect = {
  priority: "High" | "Medium" | "Low";
  status: string;
  projectAddress: string;
  submarket: string;
  councilDistrict: string;
  units: number;
  projectType: string;
  applicantDeveloper: string;
  representative: string;
  stage: string;
  opportunityFit: "High" | "Medium" | "Low";
  outreachAngle: string;
  sourceUrl: string;
  nextStep: string;
};

export const developerProspects: DeveloperProspect[] = [
  { priority:"High", status:"New Lead", projectAddress:"1833 N Wilton Pl", submarket:"Hollywood", councilDistrict:"CD 13", units:48, projectType:"100% affordable multifamily", applicantDeveloper:"Benjamin Jian Hao Zhu", representative:"Alchemy Planning", stage:"Approved 2026", opportunityFit:"High", outreachAngle:"Affordable project; may have structured lease-up needs", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/search/casenumber/EAR-2026-691-AH-SPPC-VHCA-RED1", nextStep:"Verify owner contact and construction stage" },
  { priority:"High", status:"New Lead", projectAddress:"5965 W Lexington Ave", submarket:"Hollywood Studio District", councilDistrict:"CD 13", units:52, projectType:"100% affordable multifamily", applicantDeveloper:"1200 Gordon Holding LLC", representative:"Commun Associate", stage:"Approved 2026", opportunityFit:"High", outreachAngle:"Zero parking; lease-up likely transit-oriented", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/search/casenumber/EAR-2026-731-AH-HCA-PHP", nextStep:"Verify owner contact and construction stage" },
  { priority:"High", status:"New Lead", projectAddress:"2941 W 8th St", submarket:"MacArthur Park", councilDistrict:"CD 1", units:55, projectType:"Apartment building", applicantDeveloper:"Westmoreland Los Angeles LLC", representative:"JPark Architects", stage:"Approved 2026", opportunityFit:"High", outreachAngle:"TOC project; 55 units near dense renter market", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/numericCaseId/282630", nextStep:"Verify owner contact and construction stage" },
  { priority:"Medium", status:"New Lead", projectAddress:"2217 S Fox Hills Dr", submarket:"Westside", councilDistrict:"CD 5", units:16, projectType:"Residential apartment building", applicantDeveloper:"2217 Fox Hills LLC", representative:"Beroukhim & Company LLC", stage:"On hold 2026", opportunityFit:"Medium", outreachAngle:"Small infill building; good independent lease-up target", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/casenumber/DIR-2026-2593-TOIA-VHCA", nextStep:"Verify owner contact and construction stage" },
  { priority:"Medium", status:"New Lead", projectAddress:"816 N Laguna Ave", submarket:"Echo Park", councilDistrict:"CD 1", units:25, projectType:"Multifamily building", applicantDeveloper:"Chalon Group LLC", representative:"Nur Development Consulting", stage:"Filed 2026", opportunityFit:"Medium", outreachAngle:"HPOZ project; small developer likely target", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/casenumber/DIR-2026-4625-CCMP-VHCA", nextStep:"Verify owner contact and construction stage" },
  { priority:"Medium", status:"New Lead", projectAddress:"1845 N Taft Ave", submarket:"Hollywood", councilDistrict:"CD 13", units:33, projectType:"Residential development", applicantDeveloper:"Taft Development LLC", representative:"Alchemy Planning + Land Use", stage:"On hold / terminated related ENV", opportunityFit:"Medium", outreachAngle:"Hollywood 33-unit target; verify status before outreach", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/search/casenumber/DIR-2026-479-SPPC-TOIA-VHCA", nextStep:"Verify owner contact and construction stage" },
  { priority:"High", status:"New Lead", projectAddress:"3800 W 6th St", submarket:"Koreatown", councilDistrict:"CD 10", units:299, projectType:"Mixed-use + senior building", applicantDeveloper:"3800 West Sixth Street LLC", representative:"Luciralia Ibarra Sitio", stage:"Approved 2026", opportunityFit:"High", outreachAngle:"Large lease-up opportunity; includes senior units", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/casenumber/EAR-2026-3078-DB-HCA", nextStep:"Verify owner contact and construction stage" },
  { priority:"High", status:"New Lead", projectAddress:"5451 W Adams Blvd", submarket:"West Adams", councilDistrict:"CD 10", units:142, projectType:"Mixed-use multifamily", applicantDeveloper:"5469 W. Adams (LA) LLC", representative:"Gonzales Law Group", stage:"Approved 2026", opportunityFit:"High", outreachAngle:"Large mixed-use project; likely professional lease-up need", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/numericCaseId/286434", nextStep:"Verify owner contact and construction stage" },
  { priority:"High", status:"New Lead", projectAddress:"5922 N Lemp Ave", submarket:"NoHo", councilDistrict:"CD 2", units:81, projectType:"100% affordable apartment", applicantDeveloper:"HVN Holdings LLC", representative:"Three6ixty", stage:"On hold 2026", opportunityFit:"High", outreachAngle:"Affordable 81-unit project; service/property management partners likely involved", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/casenumber/EAR-2026-4330-AH-VHCA", nextStep:"Verify owner contact and construction stage" },
  { priority:"High", status:"New Lead", projectAddress:"12508 W Pacific Ave", submarket:"Mar Vista", councilDistrict:"CD 11", units:60, projectType:"100% affordable apartment", applicantDeveloper:"12508 Pacific LLC", representative:"Three6ixty", stage:"On hold 2026", opportunityFit:"High", outreachAngle:"Westside affordable 60 units; outreach through representative", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/casenumber/EAR-2026-4729-AH-VHCA", nextStep:"Verify owner contact and construction stage" },
  { priority:"Medium", status:"New Lead", projectAddress:"3648 S Empire Dr", submarket:"Palms", councilDistrict:"CD 5", units:33, projectType:"Mixed-income building", applicantDeveloper:"HL Baldwin LLC", representative:"Not listed", stage:"Filed 2026", opportunityFit:"Medium", outreachAngle:"33-unit replacement/new construction project", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/casenumber/EAR-2026-4726-TOIA-HES", nextStep:"Verify owner contact and construction stage" },
  { priority:"High", status:"New Lead", projectAddress:"201 W Sotello St", submarket:"Historic Cultural North", councilDistrict:"CD 1", units:464, projectType:"Multifamily density bonus", applicantDeveloper:"Praxis Development Group", representative:"Three6ixty", stage:"Approved 2026", opportunityFit:"High", outreachAngle:"Very large lease-up opportunity; may have internal team but worth partner inquiry", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/numericCaseId/288415", nextStep:"Verify owner contact and construction stage" },
  { priority:"Medium", status:"New Lead", projectAddress:"3926 W Marathon St", submarket:"East Hollywood", councilDistrict:"CD 13", units:29, projectType:"Multifamily residential", applicantDeveloper:"Run Marathons LLC", representative:"Not listed", stage:"Approved 2026", opportunityFit:"Medium", outreachAngle:"29-unit infill project; small enough for independent lease-up pitch", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/numericCaseId/288440", nextStep:"Verify owner contact and construction stage" },
  { priority:"High", status:"New Lead", projectAddress:"4741 N Libbit Ave", submarket:"Encino", councilDistrict:"CD 4", units:68, projectType:"Multifamily density bonus", applicantDeveloper:"Liv Lux Properties 6 LLC", representative:"Enterprises", stage:"Approved 2026", opportunityFit:"High", outreachAngle:"68 units with VLI set-aside; likely lease-up planning needed", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/numericCaseId/278357", nextStep:"Verify owner contact and construction stage" },
  { priority:"Medium", status:"New Lead", projectAddress:"5139 Colfax Ave", submarket:"Valley Village / NoHo area", councilDistrict:"TBD", units:95, projectType:"Housing project", applicantDeveloper:"5145 Colfax LLC", representative:"TBD", stage:"Verify", opportunityFit:"Medium", outreachAngle:"Prioritize for verification in City Planning; large enough to need lease-up", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/casenumber/EAR-2026-2907-AH-SPPC-VHCA-AHS", nextStep:"Verify owner contact and construction stage" },
  { priority:"Medium", status:"New Lead", projectAddress:"1418 Mansfield Ave", submarket:"Hollywood / Mid-City", councilDistrict:"TBD", units:81, projectType:"Housing project", applicantDeveloper:"Mansfield Developments LLC", representative:"TBD", stage:"Verify", opportunityFit:"Medium", outreachAngle:"Prioritize for owner/LLC lookup and construction stage", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/casenumber/EAR-2026-2597-AH-HCA", nextStep:"Verify owner contact and construction stage" },
  { priority:"Medium", status:"New Lead", projectAddress:"5519 Elmer Ave", submarket:"NoHo", councilDistrict:"TBD", units:87, projectType:"Affordable housing project", applicantDeveloper:"Elmer 26 LLC", representative:"TBD", stage:"Verify", opportunityFit:"Medium", outreachAngle:"Prioritize for public records verification and outreach", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/search/casenumber/EAR-2026-211-AH-VHCA-RED1", nextStep:"Verify owner contact and construction stage" },
  { priority:"Medium", status:"New Lead", projectAddress:"4061 S Main St", submarket:"South LA", councilDistrict:"TBD", units:83, projectType:"Affordable housing project", applicantDeveloper:"Sasi Main LLC", representative:"TBD", stage:"Verify", opportunityFit:"Medium", outreachAngle:"South LA large project; verify stage and decision maker", sourceUrl:"https://planning.lacity.gov/pdiscaseinfo/Search/casenumber/EAR-2026-1960-AH-PHP-HCA", nextStep:"Verify owner contact and construction stage" }
];

export function leadScore(prospect: DeveloperProspect) {
  const fit = prospect.opportunityFit === "High" ? 30 : prospect.opportunityFit === "Medium" ? 20 : 10;
  const size = prospect.units >= 50 ? 30 : prospect.units >= 25 ? 20 : 10;
  const stage = prospect.stage === "Approved 2026" ? 20 : 10;
  return fit + size + stage;
}
